// Package swarm implements the PlatformAdapter interface for Docker Swarm.
//
// It uses "docker stack" commands to manage stacks as Swarm services:
//   - Generate  → produces a Swarm-compatible compose file (deploy: section added)
//   - Apply     → docker stack deploy -c <file> <stack>
//   - Stop      → scales every service to 0 replicas
//   - Start     → scales every service back to desired replicas
//   - Status    → docker service ls --filter label=com.docker.stack.namespace=<stack>
//   - Destroy   → docker stack rm + prune named volumes
//   - Diff      → compares desired replicas/image vs live service state
//   - Rollback  → Destroy (re-deploy handled by orchestrator)
package swarm

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/selvamani/stratonmesh/pkg/manifest"
	"github.com/selvamani/stratonmesh/pkg/orchestrator"
	"go.uber.org/zap"
	"gopkg.in/yaml.v3"
)

// Adapter is the Docker Swarm platform adapter.
type Adapter struct {
	logger  *zap.SugaredLogger
	workDir string // directory for generated stack files
}

var _ orchestrator.PlatformAdapter = (*Adapter)(nil)

// New creates a Swarm adapter.
func New(logger *zap.SugaredLogger, workDir string) *Adapter {
	if workDir == "" {
		workDir = "/tmp/stratonmesh/swarm"
	}
	os.MkdirAll(workDir, 0755)
	return &Adapter{logger: logger, workDir: workDir}
}

func (a *Adapter) Name() string { return "swarm" }

// Generate produces a Docker Swarm–compatible compose YAML with `deploy:` sections.
func (a *Adapter) Generate(ctx context.Context, stack *manifest.Stack) ([]byte, error) {
	cf := map[string]interface{}{
		"version":  "3.9",
		"services": map[string]interface{}{},
		"volumes":  map[string]interface{}{},
		"networks": map[string]interface{}{
			stack.Name: map[string]interface{}{"driver": "overlay", "attachable": true},
		},
	}
	svcs := cf["services"].(map[string]interface{})
	vols := cf["volumes"].(map[string]interface{})

	for _, svc := range stack.Services {
		if !svc.IsEnabled() {
			continue
		}
		replicas := svc.DefaultReplicas()

		cs := map[string]interface{}{
			"image":    svc.Image,
			"networks": []string{stack.Name},
			"deploy": map[string]interface{}{
				"replicas": replicas,
				"restart_policy": map[string]interface{}{
					"condition": "on-failure",
					"delay":     "5s",
					"max_attempts": 3,
				},
				"update_config": map[string]interface{}{
					"parallelism": 1,
					"delay":       "10s",
					"order":       "start-first",
				},
				"rollback_config": map[string]interface{}{
					"parallelism": 1,
					"delay":       "5s",
				},
			},
			"labels": map[string]string{
				"stratonmesh.stack":   stack.Name,
				"stratonmesh.service": svc.Name,
			},
		}

		// Placement constraints from affinity / node selector
		if svc.Affinity.Spread == "zone" {
			cs["deploy"].(map[string]interface{})["placement"] = map[string]interface{}{
				"preferences": []map[string]interface{}{
					{"spread": "node.labels.zone"},
				},
			}
		}
		if svc.NodeSelector != nil {
			var constraints []string
			for k, v := range svc.NodeSelector {
				constraints = append(constraints, fmt.Sprintf("node.labels.%s==%s", k, v))
			}
			cs["deploy"].(map[string]interface{})["placement"] = map[string]interface{}{
				"constraints": constraints,
			}
		}

		// Resources
		if svc.Resources.CPU != "" || svc.Resources.Memory != "" {
			res := map[string]interface{}{}
			if svc.Resources.CPU != "" {
				res["cpus"] = millicoresToDecimal(svc.Resources.CPU)
			}
			if svc.Resources.Memory != "" {
				res["memory"] = svc.Resources.Memory
			}
			cs["deploy"].(map[string]interface{})["resources"] = map[string]interface{}{
				"limits":       res,
				"reservations": res,
			}
		}

		if svc.Env != nil {
			cs["environment"] = svc.Env
		}

		var ports []string
		for _, p := range svc.Ports {
			host := p.Host
			if host == 0 {
				host = p.Expose
			}
			ports = append(ports, fmt.Sprintf("%d:%d", host, p.Expose))
		}
		if len(ports) > 0 {
			cs["ports"] = ports
		}

		var volMounts []string
		for _, v := range svc.Volumes {
			vn := fmt.Sprintf("%s-%s", stack.Name, v.Name)
			mt := v.MountAt
			if mt == "" {
				mt = "/data/" + v.Name
			}
			volMounts = append(volMounts, fmt.Sprintf("%s:%s", vn, mt))
			vols[vn] = map[string]string{"driver": "local"}
		}
		if len(volMounts) > 0 {
			cs["volumes"] = volMounts
		}

		if svc.Command != "" {
			cs["command"] = svc.Command
		}

		svcs[svc.Name] = cs
	}

	data, err := yaml.Marshal(cf)
	if err != nil {
		return nil, err
	}
	header := fmt.Sprintf("# Generated by StratonMesh (swarm): %s v%s\n\n", stack.Name, stack.Version)
	return []byte(header + string(data)), nil
}

// Apply deploys the stack to the swarm via `docker stack deploy`.
func (a *Adapter) Apply(ctx context.Context, stack *manifest.Stack) error {
	data, err := a.Generate(ctx, stack)
	if err != nil {
		return fmt.Errorf("generate swarm compose: %w", err)
	}

	p := filepath.Join(a.workDir, stack.Name+".yml")
	if err := os.WriteFile(p, data, 0644); err != nil {
		return fmt.Errorf("write compose file: %w", err)
	}

	a.logger.Infow("deploying to swarm", "stack", stack.Name, "file", p)

	var stderr bytes.Buffer
	cmd := exec.CommandContext(ctx, "docker", "stack", "deploy",
		"--compose-file", p,
		"--with-registry-auth",
		stack.Name,
	)
	cmd.Stdout = os.Stdout
	cmd.Stderr = &teeWriter{w1: os.Stderr, w2: &stderr}
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("docker stack deploy: %w\n%s", err, stderr.String())
	}
	return nil
}

// Stop scales all services in the stack to 0 replicas.
// Volumes and network are preserved; `Start` can resume them.
func (a *Adapter) Stop(ctx context.Context, stackID string) error {
	services, err := a.listSwarmServices(ctx, stackID)
	if err != nil {
		return err
	}
	for _, svcName := range services {
		out, err := exec.CommandContext(ctx, "docker", "service", "scale", fmt.Sprintf("%s=0", svcName)).CombinedOutput()
		if err != nil {
			a.logger.Warnw("scale-to-0 failed", "service", svcName, "error", string(out))
		}
	}
	a.logger.Infow("swarm stack stopped", "stack", stackID)
	return nil
}

// Start scales all services back to their desired replica count
// (reads the saved compose file to determine desired replicas).
func (a *Adapter) Start(ctx context.Context, stackID string) error {
	// Re-deploy from saved file to restore all service replica counts.
	p := filepath.Join(a.workDir, stackID+".yml")
	if _, err := os.Stat(p); err != nil {
		return fmt.Errorf("compose file for stack %q not found; re-deploy first", stackID)
	}

	var stderr bytes.Buffer
	cmd := exec.CommandContext(ctx, "docker", "stack", "deploy",
		"--compose-file", p,
		"--with-registry-auth",
		stackID,
	)
	cmd.Stdout = os.Stdout
	cmd.Stderr = &teeWriter{w1: os.Stderr, w2: &stderr}
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("docker stack deploy (start): %w\n%s", err, stderr.String())
	}
	a.logger.Infow("swarm stack started", "stack", stackID)
	return nil
}

// Status returns per-service replica and health information.
func (a *Adapter) Status(ctx context.Context, stackID string) (*orchestrator.AdapterStatus, error) {
	// docker service ls --filter label=com.docker.stack.namespace=<stack> --format json
	cmd := exec.CommandContext(ctx, "docker", "service", "ls",
		"--filter", fmt.Sprintf("label=com.docker.stack.namespace=%s", stackID),
		"--format", "{{json .}}",
	)
	out, err := cmd.Output()
	if err != nil {
		return &orchestrator.AdapterStatus{}, nil
	}

	type svcRow struct {
		Name     string `json:"Name"`     // "stack_svcname"
		Replicas string `json:"Replicas"` // "1/1" or "0/2"
		Image    string `json:"Image"`
	}

	status := &orchestrator.AdapterStatus{}
	for _, line := range bytes.Split(bytes.TrimSpace(out), []byte("\n")) {
		line = bytes.TrimSpace(line)
		if len(line) == 0 {
			continue
		}
		var row svcRow
		if err := json.Unmarshal(line, &row); err != nil {
			continue
		}
		// Parse "ready/desired" from Replicas field
		ready, desired := parseReplicaField(row.Replicas)

		// Strip stack prefix: "mystack_web" → "web"
		svcName := strings.TrimPrefix(row.Name, stackID+"_")

		health := "healthy"
		if ready < desired {
			health = "starting"
		}
		if ready == 0 && desired > 0 {
			health = "unhealthy"
		}

		status.Services = append(status.Services, orchestrator.ServiceStatus{
			Name:     svcName,
			Replicas: desired,
			Ready:    ready,
			Health:   health,
		})
	}
	return status, nil
}

// Restart triggers a rolling restart of all services in the swarm stack.
func (a *Adapter) Restart(ctx context.Context, stackID string) error {
	// List services in this stack then force-update each to trigger a restart.
	out, err := exec.CommandContext(ctx, "docker", "service", "ls",
		"--filter", fmt.Sprintf("label=com.docker.stack.namespace=%s", stackID),
		"--format", "{{.Name}}",
	).Output()
	if err != nil {
		return fmt.Errorf("list swarm services: %w", err)
	}
	for _, svcName := range strings.Fields(string(out)) {
		if o, err := exec.CommandContext(ctx, "docker", "service", "update",
			"--force", svcName).CombinedOutput(); err != nil {
			a.logger.Warnw("service restart failed", "service", svcName, "error", string(o))
		}
	}
	return nil
}

// Down removes the swarm stack services and networks but keeps named volumes.
// docker stack rm naturally does not remove named volumes.
func (a *Adapter) Down(ctx context.Context, stackID string) error {
	a.logger.Infow("bringing swarm stack down (volumes kept)", "stack", stackID)
	out, err := exec.CommandContext(ctx, "docker", "stack", "rm", stackID).CombinedOutput()
	if err != nil {
		return fmt.Errorf("docker stack rm: %w\n%s", err, string(out))
	}
	return nil
}

// Destroy removes the entire stack and its named volumes.
func (a *Adapter) Destroy(ctx context.Context, stackID string) error {
	a.logger.Infow("removing swarm stack", "stack", stackID)
	out, err := exec.CommandContext(ctx, "docker", "stack", "rm", stackID).CombinedOutput()
	if err != nil {
		return fmt.Errorf("docker stack rm: %w\n%s", err, string(out))
	}

	// Prune volumes named <stackID>-*
	volOut, _ := exec.CommandContext(ctx, "docker", "volume", "ls",
		"--filter", fmt.Sprintf("name=%s-", stackID),
		"--format", "{{.Name}}",
	).Output()
	for _, vol := range strings.Split(strings.TrimSpace(string(volOut)), "\n") {
		vol = strings.TrimSpace(vol)
		if vol == "" {
			continue
		}
		if rmOut, err := exec.CommandContext(ctx, "docker", "volume", "rm", vol).CombinedOutput(); err != nil {
			a.logger.Warnw("volume rm failed", "volume", vol, "error", string(rmOut))
		}
	}

	// Clean up the saved compose file
	os.Remove(filepath.Join(a.workDir, stackID+".yml"))

	a.logger.Infow("swarm stack destroyed", "stack", stackID)
	return nil
}

// Diff compares desired manifest against live swarm service state.
func (a *Adapter) Diff(ctx context.Context, desired, actual *manifest.Stack) (*orchestrator.DiffResult, error) {
	result := &orchestrator.DiffResult{}

	if desired == nil {
		return result, nil
	}

	// Build a map of live service states
	liveStatus, err := a.Status(ctx, desired.Name)
	if err != nil {
		return result, nil
	}
	liveMap := map[string]orchestrator.ServiceStatus{}
	for _, s := range liveStatus.Services {
		liveMap[s.Name] = s
	}

	for _, svc := range desired.Services {
		if !svc.IsEnabled() {
			continue
		}
		live, ok := liveMap[svc.Name]
		if !ok {
			result.Create = append(result.Create, svc.Name)
			continue
		}
		if svc.DefaultReplicas() != live.Replicas {
			result.Update = append(result.Update, orchestrator.UpdateAction{
				Service:    svc.Name,
				ChangeType: "replicas",
				From:       fmt.Sprintf("%d", live.Replicas),
				To:         fmt.Sprintf("%d", svc.DefaultReplicas()),
			})
		} else {
			result.Unchanged = append(result.Unchanged, svc.Name)
		}
	}
	return result, nil
}

// Rollback destroys the current deployment (orchestrator will re-deploy previous version).
func (a *Adapter) Rollback(ctx context.Context, stackID, version string) error {
	return a.Destroy(ctx, stackID)
}

// Inspect returns per-task (container) details for a service in the swarm stack.
func (a *Adapter) Inspect(ctx context.Context, stackID, service string) (*orchestrator.ServiceDetail, error) {
	svcName := fmt.Sprintf("%s_%s", stackID, service)
	detail := &orchestrator.ServiceDetail{Name: service}

	out, err := exec.CommandContext(ctx, "docker", "service", "ps",
		"--no-trunc",
		"--filter", "desired-state=running",
		"--format", "{{json .}}",
		svcName,
	).Output()
	if err != nil || len(bytes.TrimSpace(out)) == 0 {
		return detail, nil
	}

	type taskRow struct {
		ID           string `json:"ID"`
		Name         string `json:"Name"`
		Node         string `json:"Node"`
		CurrentState string `json:"CurrentState"`
		Image        string `json:"Image"`
		Error        string `json:"Error"`
	}

	for _, line := range bytes.Split(bytes.TrimSpace(out), []byte("\n")) {
		line = bytes.TrimSpace(line)
		if len(line) == 0 {
			continue
		}
		var task taskRow
		if json.Unmarshal(line, &task) != nil {
			continue
		}
		if detail.Image == "" {
			detail.Image = task.Image
		}
		state := strings.ToLower(task.CurrentState)
		health := "running"
		if !strings.Contains(state, "running") {
			health = state
		}
		detail.Instances = append(detail.Instances, orchestrator.InstanceInfo{
			ID:     task.ID[:min12(task.ID)],
			Name:   task.Name,
			Status: state,
			Health: health,
			Node:   task.Node,
		})
	}
	return detail, nil
}

// Logs returns recent log lines for a service via docker service logs.
func (a *Adapter) Logs(ctx context.Context, stackID, service string, tail int) (string, error) {
	if tail <= 0 {
		tail = 100
	}
	svcName := fmt.Sprintf("%s_%s", stackID, service)
	out, _ := exec.CommandContext(ctx, "docker", "service", "logs",
		"--no-trunc", "--timestamps",
		fmt.Sprintf("--tail=%d", tail),
		svcName,
	).CombinedOutput()
	return string(out), nil
}

// LogStream opens a live docker service logs --follow stream.
func (a *Adapter) LogStream(ctx context.Context, stackID, service string) (io.ReadCloser, error) {
	svcName := fmt.Sprintf("%s_%s", stackID, service)
	cmd := exec.CommandContext(ctx, "docker", "service", "logs",
		"--follow", "--no-trunc", "--timestamps", "--tail=50", svcName,
	)
	pr, pw := io.Pipe()
	cmd.Stdout = pw
	cmd.Stderr = pw
	if err := cmd.Start(); err != nil {
		pw.Close()
		return nil, fmt.Errorf("docker service logs: %w", err)
	}
	go func() {
		cmd.Wait() //nolint:errcheck
		pw.Close()
	}()
	return pr, nil
}

func min12(s string) int {
	if len(s) > 12 {
		return 12
	}
	return len(s)
}

// --- helpers ---

// listSwarmServices returns all service names in the form "<stack>_<svc>" for a stack.
func (a *Adapter) listSwarmServices(ctx context.Context, stackID string) ([]string, error) {
	out, err := exec.CommandContext(ctx, "docker", "service", "ls",
		"--filter", fmt.Sprintf("label=com.docker.stack.namespace=%s", stackID),
		"--format", "{{.Name}}",
		"--quiet",
	).Output()
	if err != nil {
		return nil, err
	}
	var names []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if line = strings.TrimSpace(line); line != "" {
			names = append(names, line)
		}
	}
	return names, nil
}

// parseReplicaField parses "ready/desired" from docker service ls Replicas column.
func parseReplicaField(s string) (ready, desired int) {
	parts := strings.SplitN(s, "/", 2)
	if len(parts) != 2 {
		return 0, 0
	}
	fmt.Sscanf(strings.TrimSpace(parts[0]), "%d", &ready)
	fmt.Sscanf(strings.TrimSpace(parts[1]), "%d", &desired)
	return
}

// millicoresToDecimal converts "500m" → "0.5", "2000m" → "2.0".
func millicoresToDecimal(s string) string {
	var mc int
	if _, err := fmt.Sscanf(s, "%dm", &mc); err == nil {
		return fmt.Sprintf("%.3f", float64(mc)/1000.0)
	}
	return s
}

type teeWriter struct {
	w1, w2 interface{ Write([]byte) (int, error) }
}

func (t *teeWriter) Write(p []byte) (int, error) {
	t.w1.Write(p) //nolint:errcheck
	return t.w2.Write(p)
}
