// Package nomad implements the PlatformAdapter interface for HashiCorp Nomad.
//
// It generates Nomad job HCL files and submits them via the Nomad CLI:
//   - Generate  → produces a Nomad job spec in HCL
//   - Apply     → nomad job run <file>
//   - Stop      → nomad job stop (keeps allocations for later restart)
//   - Start     → nomad job run (resumes from saved spec)
//   - Status    → nomad job status -json
//   - Inspect   → nomad alloc status for each running allocation
//   - Logs      → nomad alloc logs
//   - Destroy   → nomad job stop -purge
//   - Diff      → compares desired replicas vs live task group counts
//   - Rollback  → nomad job revert
package nomad

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/selvamani/stratonmesh/pkg/manifest"
	"github.com/selvamani/stratonmesh/pkg/orchestrator"
	"go.uber.org/zap"
)

// Adapter is the Nomad platform adapter.
type Adapter struct {
	logger    *zap.SugaredLogger
	workDir   string
	nomadAddr string // NOMAD_ADDR override (empty = use env)
}

var _ orchestrator.PlatformAdapter = (*Adapter)(nil)

// New creates a Nomad adapter.
func New(logger *zap.SugaredLogger, nomadAddr string) *Adapter {
	workDir := "/tmp/stratonmesh/nomad"
	os.MkdirAll(workDir, 0755)
	return &Adapter{logger: logger, workDir: workDir, nomadAddr: nomadAddr}
}

func (a *Adapter) Name() string { return "nomad" }

// Generate produces a Nomad job HCL file from the stack manifest.
func (a *Adapter) Generate(ctx context.Context, stack *manifest.Stack) ([]byte, error) {
	var hcl strings.Builder
	hcl.WriteString(fmt.Sprintf("# Generated by StratonMesh: %s v%s\n\n", stack.Name, stack.Version))
	hcl.WriteString(fmt.Sprintf("job \"%s\" {\n", stack.Name))
	hcl.WriteString(fmt.Sprintf("  datacenters = [\"dc1\"]\n"))
	hcl.WriteString(fmt.Sprintf("  type        = \"service\"\n\n"))
	hcl.WriteString(fmt.Sprintf("  meta {\n    stratonmesh_stack = \"%s\"\n    version           = \"%s\"\n  }\n\n",
		stack.Name, stack.Version))

	for _, svc := range stack.Services {
		if !svc.IsEnabled() {
			continue
		}

		// Choose scheduler type by workload archetype.
		jobType := "service"
		switch svc.InferType() {
		case manifest.WorkloadBatch:
			jobType = "batch"
		case manifest.WorkloadScheduled:
			jobType = "batch" // wrap in periodic block below
		case manifest.WorkloadDaemon:
			jobType = "system"
		}

		hcl.WriteString(fmt.Sprintf("  group \"%s\" {\n", svc.Name))
		if jobType != "system" {
			hcl.WriteString(fmt.Sprintf("    count = %d\n\n", svc.DefaultReplicas()))
		}

		// Periodic block for scheduled workloads.
		if svc.InferType() == manifest.WorkloadScheduled && svc.Schedule != "" {
			hcl.WriteString(fmt.Sprintf("    periodic {\n      cron = \"%s\"\n    }\n\n", svc.Schedule))
		}

		// Network / ports.
		if len(svc.Ports) > 0 {
			hcl.WriteString("    network {\n")
			for _, p := range svc.Ports {
				host := p.Host
				if host == 0 {
					host = p.Expose
				}
				hcl.WriteString(fmt.Sprintf("      port \"%s\" { static = %d to = %d }\n",
					svc.Name, host, p.Expose))
			}
			hcl.WriteString("    }\n\n")
		}

		// Volume mounts.
		for _, v := range svc.Volumes {
			hcl.WriteString(fmt.Sprintf("    volume \"%s\" {\n      type   = \"host\"\n      source = \"%s-%s\"\n    }\n\n",
				v.Name, stack.Name, v.Name))
		}

		// Task block.
		hcl.WriteString(fmt.Sprintf("    task \"%s\" {\n", svc.Name))
		hcl.WriteString("      driver = \"docker\"\n\n")
		hcl.WriteString("      config {\n")
		hcl.WriteString(fmt.Sprintf("        image = \"%s\"\n", svc.Image))
		if len(svc.Ports) > 0 {
			portLabels := make([]string, 0, len(svc.Ports))
			for _, p := range svc.Ports {
				portLabels = append(portLabels, fmt.Sprintf("\"%s\"", svc.Name))
				_ = p
			}
			hcl.WriteString(fmt.Sprintf("        ports = [%s]\n", strings.Join(portLabels, ", ")))
		}
		if svc.Command != "" {
			parts := strings.Fields(svc.Command)
			hcl.WriteString(fmt.Sprintf("        command = \"%s\"\n", parts[0]))
			if len(parts) > 1 {
				args := make([]string, len(parts)-1)
				for i, a := range parts[1:] {
					args[i] = fmt.Sprintf("%q", a)
				}
				hcl.WriteString(fmt.Sprintf("        args    = [%s]\n", strings.Join(args, ", ")))
			}
		}
		hcl.WriteString("      }\n\n")

		// Env vars.
		if len(svc.Env) > 0 {
			hcl.WriteString("      env {\n")
			for k, v := range svc.Env {
				hcl.WriteString(fmt.Sprintf("        %s = \"%s\"\n", k, v))
			}
			hcl.WriteString("      }\n\n")
		}

		// Resources.
		hcl.WriteString("      resources {\n")
		if svc.Resources.CPU != "" {
			mc := parseMilli(svc.Resources.CPU)
			hcl.WriteString(fmt.Sprintf("        cpu    = %d\n", mc))
		} else {
			hcl.WriteString("        cpu    = 250\n")
		}
		if svc.Resources.Memory != "" {
			mb := parseMiB(svc.Resources.Memory)
			hcl.WriteString(fmt.Sprintf("        memory = %d\n", mb))
		} else {
			hcl.WriteString("        memory = 128\n")
		}
		hcl.WriteString("      }\n\n")

		// Restart policy.
		hcl.WriteString("      restart {\n        attempts = 3\n        delay    = \"15s\"\n        mode     = \"fail\"\n      }\n")
		hcl.WriteString("    }\n")  // end task
		hcl.WriteString("  }\n\n") // end group
	}

	hcl.WriteString("}\n")
	return []byte(hcl.String()), nil
}

// Apply submits the job to Nomad via `nomad job run`.
func (a *Adapter) Apply(ctx context.Context, stack *manifest.Stack) error {
	data, err := a.Generate(ctx, stack)
	if err != nil {
		return fmt.Errorf("generate nomad job: %w", err)
	}
	p := filepath.Join(a.workDir, stack.Name+".nomad")
	if err := os.WriteFile(p, data, 0644); err != nil {
		return fmt.Errorf("write job file: %w", err)
	}
	a.logger.Infow("submitting nomad job", "stack", stack.Name, "file", p)

	var stderr bytes.Buffer
	cmd := a.cmd(ctx, "nomad", "job", "run", p)
	cmd.Stdout = os.Stdout
	cmd.Stderr = &teeWriter{w1: os.Stderr, w2: &stderr}
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("nomad job run: %w\n%s", err, stderr.String())
	}
	return nil
}

// Stop pauses all task groups (sets count = 0) without purging the job.
func (a *Adapter) Stop(ctx context.Context, stackID string) error {
	cmd := a.cmd(ctx, "nomad", "job", "stop", stackID)
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("nomad job stop: %w", err)
	}
	a.logger.Infow("nomad job stopped (not purged)", "stack", stackID)
	return nil
}

// Restart stops the job then immediately re-submits it.
func (a *Adapter) Restart(ctx context.Context, stackID string) error {
	if err := a.Stop(ctx, stackID); err != nil {
		return err
	}
	return a.Start(ctx, stackID)
}

// Down stops the Nomad job without purging it. Allocations are removed,
// the job definition and any host-mounted data are preserved.
// This is equivalent to Stop for Nomad since `nomad job stop` deregisters
// all allocations without touching persistent data on the host.
func (a *Adapter) Down(ctx context.Context, stackID string) error {
	return a.Stop(ctx, stackID)
}

// Start re-submits the saved job file, resuming all task groups.
func (a *Adapter) Start(ctx context.Context, stackID string) error {
	p := filepath.Join(a.workDir, stackID+".nomad")
	if _, err := os.Stat(p); err != nil {
		return fmt.Errorf("job spec for %q not found; re-deploy first", stackID)
	}
	cmd := a.cmd(ctx, "nomad", "job", "run", p)
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("nomad job run (start): %w", err)
	}
	a.logger.Infow("nomad job started", "stack", stackID)
	return nil
}

// Status returns per-task-group health from `nomad job status -json`.
func (a *Adapter) Status(ctx context.Context, stackID string) (*orchestrator.AdapterStatus, error) {
	out, err := a.cmd(ctx, "nomad", "job", "status", "-json", stackID).Output()
	if err != nil {
		return &orchestrator.AdapterStatus{}, nil
	}

	var jobStatus struct {
		TaskGroups []struct {
			Name    string `json:"Name"`
			Count   int    `json:"Count"`
			Summary struct {
				Running int `json:"Running"`
				Failed  int `json:"Failed"`
			} `json:"Summary"`
		} `json:"TaskGroups"`
	}
	if json.Unmarshal(out, &jobStatus) != nil {
		return &orchestrator.AdapterStatus{}, nil
	}

	status := &orchestrator.AdapterStatus{}
	for _, tg := range jobStatus.TaskGroups {
		health := "healthy"
		if tg.Summary.Running < tg.Count {
			health = "starting"
		}
		if tg.Summary.Running == 0 && tg.Count > 0 {
			health = "unhealthy"
		}
		status.Services = append(status.Services, orchestrator.ServiceStatus{
			Name:     tg.Name,
			Replicas: tg.Count,
			Ready:    tg.Summary.Running,
			Health:   health,
		})
	}
	return status, nil
}

// Inspect returns allocation-level details for a task group (service).
func (a *Adapter) Inspect(ctx context.Context, stackID, service string) (*orchestrator.ServiceDetail, error) {
	detail := &orchestrator.ServiceDetail{Name: service, Platform: "nomad"}

	// List allocations for this job/task group.
	out, err := a.cmd(ctx, "nomad", "alloc", "list",
		"-json",
		"-job", stackID,
	).Output()
	if err != nil {
		return detail, nil
	}

	var allocs []struct {
		ID          string `json:"ID"`
		Name        string `json:"Name"`
		NodeName    string `json:"NodeName"`
		ClientStatus string `json:"ClientStatus"`
		TaskGroup   string `json:"TaskGroup"`
		CreateTime  int64  `json:"CreateTime"`
	}
	if json.Unmarshal(out, &allocs) != nil {
		return detail, nil
	}

	for _, alloc := range allocs {
		if alloc.TaskGroup != service {
			continue
		}
		health := "unknown"
		if alloc.ClientStatus == "running" {
			health = "running"
		} else if alloc.ClientStatus == "failed" || alloc.ClientStatus == "lost" {
			health = "unhealthy"
		}
		detail.Instances = append(detail.Instances, orchestrator.InstanceInfo{
			ID:     alloc.ID[:min12(alloc.ID)],
			Name:   alloc.Name,
			Status: alloc.ClientStatus,
			Health: health,
			Node:   alloc.NodeName,
		})
	}
	return detail, nil
}

// Logs returns recent log lines for a task via `nomad alloc logs`.
func (a *Adapter) Logs(ctx context.Context, stackID, service string, tail int) (string, error) {
	if tail <= 0 {
		tail = 100
	}
	// Find the most recent running allocation for this task group.
	out, err := a.cmd(ctx, "nomad", "alloc", "list", "-json", "-job", stackID).Output()
	if err != nil {
		return "", nil
	}
	var allocs []struct {
		ID          string `json:"ID"`
		TaskGroup   string `json:"TaskGroup"`
		ClientStatus string `json:"ClientStatus"`
	}
	if json.Unmarshal(out, &allocs) != nil {
		return "", nil
	}
	var allocID string
	for _, a := range allocs {
		if a.TaskGroup == service && a.ClientStatus == "running" {
			allocID = a.ID
			break
		}
	}
	if allocID == "" {
		return "(no running allocation found)", nil
	}

	logOut, _ := a.cmd(ctx, "nomad", "alloc", "logs",
		"-tail", "-n", fmt.Sprintf("%d", tail),
		allocID, service,
	).Output()
	return string(logOut), nil
}

// LogStream opens a live nomad alloc logs -follow stream.
func (a *Adapter) LogStream(ctx context.Context, stackID, service string) (io.ReadCloser, error) {
	out, _ := a.Logs(ctx, stackID, service, 50)
	return io.NopCloser(strings.NewReader(out)), nil
}

// Destroy permanently removes the job (purge) and its data.
func (a *Adapter) Destroy(ctx context.Context, stackID string) error {
	cmd := a.cmd(ctx, "nomad", "job", "stop", "-purge", stackID)
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("nomad job stop -purge: %w", err)
	}
	os.Remove(filepath.Join(a.workDir, stackID+".nomad"))
	a.logger.Infow("nomad job destroyed", "stack", stackID)
	return nil
}

// Diff compares desired replica counts against the live Nomad job state.
func (a *Adapter) Diff(ctx context.Context, desired, actual *manifest.Stack) (*orchestrator.DiffResult, error) {
	result := &orchestrator.DiffResult{}
	if desired == nil {
		return result, nil
	}
	live, err := a.Status(ctx, desired.Name)
	if err != nil {
		return result, nil
	}
	liveMap := map[string]orchestrator.ServiceStatus{}
	for _, s := range live.Services {
		liveMap[s.Name] = s
	}
	for _, svc := range desired.Services {
		if !svc.IsEnabled() {
			continue
		}
		ls, ok := liveMap[svc.Name]
		if !ok {
			result.Create = append(result.Create, svc.Name)
			continue
		}
		if svc.DefaultReplicas() != ls.Replicas {
			result.Update = append(result.Update, orchestrator.UpdateAction{
				Service:    svc.Name,
				ChangeType: "replicas",
				From:       fmt.Sprintf("%d", ls.Replicas),
				To:         fmt.Sprintf("%d", svc.DefaultReplicas()),
			})
		} else {
			result.Unchanged = append(result.Unchanged, svc.Name)
		}
	}
	return result, nil
}

// Rollback reverts to the previous job version via `nomad job revert`.
func (a *Adapter) Rollback(ctx context.Context, stackID, version string) error {
	// Nomad tracks job versions internally; revert to index N-1.
	cmd := a.cmd(ctx, "nomad", "job", "revert", stackID, "1")
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	return cmd.Run()
}

// --- helpers ---

// cmd builds an exec.Cmd with the optional NOMAD_ADDR override applied.
func (a *Adapter) cmd(ctx context.Context, name string, args ...string) *exec.Cmd {
	cmd := exec.CommandContext(ctx, name, args...)
	if a.nomadAddr != "" {
		cmd.Env = append(os.Environ(), "NOMAD_ADDR="+a.nomadAddr)
	}
	return cmd
}

// parseMilli parses "500m" → 500 (CPU MHz for Nomad).
func parseMilli(s string) int {
	var mc int
	if _, err := fmt.Sscanf(s, "%dm", &mc); err == nil {
		return mc
	}
	var f float64
	fmt.Sscanf(s, "%f", &f)
	return int(f * 1000)
}

// parseMiB parses "128Mi" or "256M" → MiB integer.
func parseMiB(s string) int {
	s = strings.TrimSpace(s)
	var n int
	fmt.Sscanf(s, "%d", &n)
	if strings.Contains(s, "Gi") || strings.Contains(s, "G") {
		return n * 1024
	}
	return n
}

func min12(s string) int {
	if len(s) > 12 {
		return 12
	}
	return len(s)
}

type teeWriter struct {
	w1, w2 interface{ Write([]byte) (int, error) }
}

func (t *teeWriter) Write(p []byte) (int, error) {
	t.w1.Write(p) //nolint:errcheck
	return t.w2.Write(p)
}
