package compose

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/stratonmesh/stratonmesh/pkg/manifest"
	"github.com/stratonmesh/stratonmesh/pkg/orchestrator"
	"go.uber.org/zap"
	"gopkg.in/yaml.v3"
)

type Adapter struct {
	logger  *zap.SugaredLogger
	workDir string
}

var _ orchestrator.PlatformAdapter = (*Adapter)(nil)

func New(logger *zap.SugaredLogger, workDir string) *Adapter {
	if workDir == "" { workDir = "/tmp/stratonmesh/compose" }
	os.MkdirAll(workDir, 0755)
	return &Adapter{logger: logger, workDir: workDir}
}

func (a *Adapter) Name() string { return "compose" }

func (a *Adapter) Generate(ctx context.Context, stack *manifest.Stack) ([]byte, error) {
	cf := map[string]interface{}{
		"version": "3.9",
		"services": map[string]interface{}{},
		"volumes": map[string]interface{}{},
		"networks": map[string]interface{}{stack.Name: map[string]string{"driver": "bridge"}},
	}
	svcs := cf["services"].(map[string]interface{})
	vols := cf["volumes"].(map[string]interface{})

	for _, svc := range stack.Services {
		if !svc.IsEnabled() { continue }
		cs := map[string]interface{}{
			"image": svc.Image,
			"restart": "unless-stopped",
			"networks": []string{stack.Name},
			"labels": map[string]string{
				"stratonmesh.stack": stack.Name,
				"stratonmesh.service": svc.Name,
			},
		}
		if svc.Env != nil { cs["environment"] = svc.Env }
		if svc.DefaultReplicas() > 1 {
			cs["deploy"] = map[string]interface{}{"replicas": svc.DefaultReplicas()}
		}
		var ports []string
		for _, p := range svc.Ports { ports = append(ports, fmt.Sprintf("%d", p.Expose)) }
		if len(ports) > 0 { cs["ports"] = ports }
		var volMounts []string
		for _, v := range svc.Volumes {
			vn := fmt.Sprintf("%s-%s", stack.Name, v.Name)
			mt := v.MountAt; if mt == "" { mt = "/data/" + v.Name }
			volMounts = append(volMounts, fmt.Sprintf("%s:%s", vn, mt))
			vols[vn] = map[string]string{"driver": "local"}
		}
		if len(volMounts) > 0 { cs["volumes"] = volMounts }
		if len(svc.DependsOn) > 0 {
			deps := make(map[string]map[string]string)
			for _, d := range svc.DependsOn { deps[d] = map[string]string{"condition": "service_healthy"} }
			cs["depends_on"] = deps
		}
		if svc.Command != "" { cs["command"] = svc.Command }
		svcs[svc.Name] = cs
	}
	data, _ := yaml.Marshal(cf)
	header := fmt.Sprintf("# Generated by StratonMesh: %s v%s\n\n", stack.Name, stack.Version)
	return []byte(header + string(data)), nil
}

func (a *Adapter) Apply(ctx context.Context, stack *manifest.Stack) error {
	if stack.Metadata.RepoPath != "" {
		return a.applyFromRepo(ctx, stack)
	}
	data, err := a.Generate(ctx, stack)
	if err != nil { return err }
	p := filepath.Join(a.workDir, stack.Name, "docker-compose.yml")
	os.MkdirAll(filepath.Dir(p), 0755)
	os.WriteFile(p, data, 0644)
	cmd := exec.CommandContext(ctx, "docker", "compose", "-f", p, "-p", stack.Name, "up", "-d")
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	return cmd.Run()
}

// applyFromRepo builds images from local source then starts the stack.
// Uses `docker compose up --build -d` so compose handles build+start atomically.
func (a *Adapter) applyFromRepo(ctx context.Context, stack *manifest.Stack) error {
	var composePath string
	if stack.Metadata.DeployFile != "" {
		composePath = filepath.Join(stack.Metadata.RepoPath, stack.Metadata.DeployFile)
	} else {
		composePath = a.findComposeFile(stack.Metadata.RepoPath)
	}
	if composePath == "" {
		return fmt.Errorf("no docker-compose file found in repo %s", stack.Metadata.RepoPath)
	}
	// Persist a pointer so Destroy can locate the compose file without the manifest.
	stackDir := filepath.Join(a.workDir, stack.Name)
	os.MkdirAll(stackDir, 0755)
	os.WriteFile(filepath.Join(stackDir, "repo-path"), []byte(stack.Metadata.RepoPath), 0644)

	a.logger.Infow("deploying from source repo", "stack", stack.Name, "compose", composePath)

	var stderr bytes.Buffer
	cmd := exec.CommandContext(ctx, "docker", "compose",
		"-f", composePath,
		"-p", stack.Name,
		"up", "--build", "-d",
	)
	cmd.Stdout = os.Stdout
	cmd.Stderr = &teeWriter{w1: os.Stderr, w2: &stderr}
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("docker compose up --build: %w\n%s", err, stderr.String())
	}
	return nil
}

// teeWriter writes to two writers simultaneously.
type teeWriter struct {
	w1, w2 interface{ Write([]byte) (int, error) }
}

func (t *teeWriter) Write(p []byte) (int, error) {
	t.w1.Write(p) //nolint:errcheck
	return t.w2.Write(p)
}

func (a *Adapter) findComposeFile(repoPath string) string {
	for _, name := range []string{"docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"} {
		if _, err := os.Stat(filepath.Join(repoPath, name)); err == nil {
			return filepath.Join(repoPath, name)
		}
	}
	return ""
}

func (a *Adapter) Status(ctx context.Context, id string) (*orchestrator.AdapterStatus, error) {
	return &orchestrator.AdapterStatus{}, nil
}

func (a *Adapter) Destroy(ctx context.Context, id string) error {
	composePath := filepath.Join(a.workDir, id, "docker-compose.yml")
	// For repo-mode stacks, find the original compose file via the pointer we wrote.
	if data, err := os.ReadFile(filepath.Join(a.workDir, id, "repo-path")); err == nil {
		if p := a.findComposeFile(string(data)); p != "" {
			composePath = p
		}
	}
	cmd := exec.CommandContext(ctx, "docker", "compose", "-f", composePath, "-p", id, "down", "-v")
	return cmd.Run()
}
func (a *Adapter) Diff(ctx context.Context, desired, actual *manifest.Stack) (*orchestrator.DiffResult, error) {
	return &orchestrator.DiffResult{}, nil
}
func (a *Adapter) Rollback(ctx context.Context, id, ver string) error { return a.Destroy(ctx, id) }
