package kubernetes

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os/exec"
	"strings"

	"github.com/selvamani/stratonmesh/pkg/manifest"
	"github.com/selvamani/stratonmesh/pkg/orchestrator"
	"go.uber.org/zap"
	"gopkg.in/yaml.v3"
)

type Adapter struct {
	logger    *zap.SugaredLogger
	namespace string
}

var _ orchestrator.PlatformAdapter = (*Adapter)(nil)

func New(logger *zap.SugaredLogger, namespace string) *Adapter {
	if namespace == "" { namespace = "default" }
	return &Adapter{logger: logger, namespace: namespace}
}

func (a *Adapter) Name() string { return "kubernetes" }

func (a *Adapter) Generate(ctx context.Context, stack *manifest.Stack) ([]byte, error) {
	ns := stack.Environment
	if ns == "" { ns = stack.Name }
	var docs []string

	for _, svc := range stack.Services {
		if !svc.IsEnabled() { continue }
		labels := map[string]string{"app": svc.Name, "stratonmesh.io/stack": stack.Name}
		kind := "Deployment"
		apiVer := "apps/v1"
		spec := map[string]interface{}{
			"replicas": svc.DefaultReplicas(),
			"selector": map[string]interface{}{"matchLabels": labels},
			"template": map[string]interface{}{
				"metadata": map[string]interface{}{"labels": labels},
				"spec": map[string]interface{}{
					"containers": []interface{}{buildContainer(svc)},
				},
			},
		}
		switch svc.InferType() {
		case manifest.WorkloadStateful:
			kind = "StatefulSet"
			spec["serviceName"] = svc.Name
		case manifest.WorkloadBatch:
			kind, apiVer = "Job", "batch/v1"
			delete(spec, "replicas"); delete(spec, "selector")
			spec["backoffLimit"] = svc.Retries
		case manifest.WorkloadScheduled:
			kind, apiVer = "CronJob", "batch/v1"
			spec = map[string]interface{}{"schedule": svc.Schedule, "jobTemplate": map[string]interface{}{"spec": spec}}
			delete(spec["jobTemplate"].(map[string]interface{})["spec"].(map[string]interface{}), "replicas")
		case manifest.WorkloadDaemon:
			kind = "DaemonSet"
			delete(spec, "replicas")
		}
		res := map[string]interface{}{
			"apiVersion": apiVer, "kind": kind,
			"metadata": map[string]interface{}{"name": svc.Name, "namespace": ns, "labels": labels},
			"spec": spec,
		}
		d, _ := yaml.Marshal(res)
		docs = append(docs, string(d))

		if len(svc.Ports) > 0 {
			var ports []interface{}
			for _, p := range svc.Ports {
				ports = append(ports, map[string]interface{}{"port": p.Expose, "targetPort": p.Expose, "protocol": "TCP"})
			}
			svcRes, _ := yaml.Marshal(map[string]interface{}{
				"apiVersion": "v1", "kind": "Service",
				"metadata": map[string]interface{}{"name": svc.Name, "namespace": ns},
				"spec": map[string]interface{}{"selector": labels, "ports": ports},
			})
			docs = append(docs, string(svcRes))
		}
	}
	return []byte("# Generated by StratonMesh\n---\n" + strings.Join(docs, "\n---\n")), nil
}

func buildContainer(svc manifest.Service) map[string]interface{} {
	c := map[string]interface{}{"name": svc.Name, "image": svc.Image}
	var ports []interface{}
	for _, p := range svc.Ports { ports = append(ports, map[string]interface{}{"containerPort": p.Expose}) }
	if len(ports) > 0 { c["ports"] = ports }
	var env []interface{}
	for k, v := range svc.Env {
		env = append(env, map[string]interface{}{"name": k, "value": v})
	}
	if len(env) > 0 { c["env"] = env }
	if svc.Resources.CPU != "" || svc.Resources.Memory != "" {
		r := map[string]string{}
		if svc.Resources.CPU != "" { r["cpu"] = svc.Resources.CPU }
		if svc.Resources.Memory != "" { r["memory"] = svc.Resources.Memory }
		c["resources"] = map[string]interface{}{"requests": r, "limits": r}
	}
	if svc.HealthCheck.Liveness != nil && svc.HealthCheck.Liveness.HTTP != "" {
		port := 80; if len(svc.Ports) > 0 { port = svc.Ports[0].Expose }
		c["livenessProbe"] = map[string]interface{}{"httpGet": map[string]interface{}{"path": svc.HealthCheck.Liveness.HTTP, "port": port}}
	}
	if svc.Command != "" { c["command"] = strings.Fields(svc.Command) }
	return c
}

func (a *Adapter) Apply(ctx context.Context, stack *manifest.Stack) error {
	data, err := a.Generate(ctx, stack)
	if err != nil { return err }
	a.logger.Infow("kubernetes manifests generated", "stack", stack.Name, "bytes", len(data))
	// TODO: client-go server-side apply
	return nil
}
func (a *Adapter) Status(ctx context.Context, id string) (*orchestrator.AdapterStatus, error) { return &orchestrator.AdapterStatus{}, nil }
func (a *Adapter) Stop(ctx context.Context, id string) error    { return nil }
func (a *Adapter) Start(ctx context.Context, id string) error   { return nil }
// Restart triggers a rolling restart of all deployments in the stack.
func (a *Adapter) Restart(ctx context.Context, id string) error {
	label := fmt.Sprintf("stratonmesh.io/stack=%s", id)
	exec.CommandContext(ctx, "kubectl", "rollout", "restart", "deployment",
		"-n", a.namespace, "-l", label).Run()
	return nil
}
// Down deletes workloads and services, but preserves PersistentVolumeClaims.
func (a *Adapter) Down(ctx context.Context, id string) error {
	label := fmt.Sprintf("stratonmesh.io/stack=%s", id)
	exec.CommandContext(ctx, "kubectl", "delete", "deployment,service,daemonset,statefulset",
		"-n", a.namespace, "-l", label).Run()
	return nil
}
func (a *Adapter) Destroy(ctx context.Context, id string) error { return nil }
func (a *Adapter) Diff(ctx context.Context, d, act *manifest.Stack) (*orchestrator.DiffResult, error) { return &orchestrator.DiffResult{}, nil }
func (a *Adapter) Rollback(ctx context.Context, id, v string) error { return nil }

// Inspect returns per-pod details for a Kubernetes service.
func (a *Adapter) Inspect(ctx context.Context, stackID, service string) (*orchestrator.ServiceDetail, error) {
	detail := &orchestrator.ServiceDetail{Name: service}

	out, err := exec.CommandContext(ctx, "kubectl", "get", "pods",
		"-n", a.namespace,
		"-l", fmt.Sprintf("app=%s,stratonmesh.io/stack=%s", service, stackID),
		"-o", "json",
	).Output()
	if err != nil {
		return detail, nil
	}

	var podList struct {
		Items []struct {
			Metadata struct {
				Name string `json:"name"`
			} `json:"metadata"`
			Spec struct {
				NodeName   string `json:"nodeName"`
				Containers []struct {
					Image string `json:"image"`
				} `json:"containers"`
			} `json:"spec"`
			Status struct {
				Phase     string `json:"phase"`
				StartTime string `json:"startTime"`
			} `json:"status"`
		} `json:"items"`
	}
	if json.Unmarshal(out, &podList) != nil {
		return detail, nil
	}

	for _, pod := range podList.Items {
		if len(pod.Spec.Containers) > 0 && detail.Image == "" {
			detail.Image = pod.Spec.Containers[0].Image
		}
		phase := strings.ToLower(pod.Status.Phase)
		health := "unknown"
		if phase == "running" {
			health = "running"
		} else if phase == "failed" {
			health = "unhealthy"
		}
		detail.Instances = append(detail.Instances, orchestrator.InstanceInfo{
			ID:      pod.Metadata.Name,
			Name:    pod.Metadata.Name,
			Status:  phase,
			Health:  health,
			Node:    pod.Spec.NodeName,
			Started: pod.Status.StartTime,
		})
	}
	return detail, nil
}

// Logs returns recent log lines for a Kubernetes service via kubectl logs.
func (a *Adapter) Logs(ctx context.Context, stackID, service string, tail int) (string, error) {
	if tail <= 0 {
		tail = 100
	}
	out, _ := exec.CommandContext(ctx, "kubectl", "logs",
		"-n", a.namespace,
		"-l", fmt.Sprintf("app=%s", service),
		fmt.Sprintf("--tail=%d", tail),
		"--timestamps",
	).Output()
	return string(out), nil
}

// LogStream opens a live kubectl logs --follow stream for the service.
func (a *Adapter) LogStream(ctx context.Context, stackID, service string) (io.ReadCloser, error) {
	cmd := exec.CommandContext(ctx, "kubectl", "logs",
		"-n", a.namespace,
		"-l", fmt.Sprintf("app=%s", service),
		"--follow", "--tail=50", "--timestamps",
	)
	pr, pw := io.Pipe()
	cmd.Stdout = pw
	cmd.Stderr = pw
	if err := cmd.Start(); err != nil {
		pw.Close()
		return nil, fmt.Errorf("kubectl logs: %w", err)
	}
	go func() {
		cmd.Wait() //nolint:errcheck
		pw.Close()
	}()
	return pr, nil
}
