package kubernetes

import (
	"context"
	"strings"

	"github.com/stratonmesh/stratonmesh/pkg/manifest"
	"github.com/stratonmesh/stratonmesh/pkg/orchestrator"
	"go.uber.org/zap"
	"gopkg.in/yaml.v3"
)

type Adapter struct {
	logger    *zap.SugaredLogger
	namespace string
}

var _ orchestrator.PlatformAdapter = (*Adapter)(nil)

func New(logger *zap.SugaredLogger, namespace string) *Adapter {
	if namespace == "" { namespace = "default" }
	return &Adapter{logger: logger, namespace: namespace}
}

func (a *Adapter) Name() string { return "kubernetes" }

func (a *Adapter) Generate(ctx context.Context, stack *manifest.Stack) ([]byte, error) {
	ns := stack.Environment
	if ns == "" { ns = stack.Name }
	var docs []string

	for _, svc := range stack.Services {
		if !svc.IsEnabled() { continue }
		labels := map[string]string{"app": svc.Name, "stratonmesh.io/stack": stack.Name}
		kind := "Deployment"
		apiVer := "apps/v1"
		spec := map[string]interface{}{
			"replicas": svc.DefaultReplicas(),
			"selector": map[string]interface{}{"matchLabels": labels},
			"template": map[string]interface{}{
				"metadata": map[string]interface{}{"labels": labels},
				"spec": map[string]interface{}{
					"containers": []interface{}{buildContainer(svc)},
				},
			},
		}
		switch svc.InferType() {
		case manifest.WorkloadStateful:
			kind = "StatefulSet"
			spec["serviceName"] = svc.Name
		case manifest.WorkloadBatch:
			kind, apiVer = "Job", "batch/v1"
			delete(spec, "replicas"); delete(spec, "selector")
			spec["backoffLimit"] = svc.Retries
		case manifest.WorkloadScheduled:
			kind, apiVer = "CronJob", "batch/v1"
			spec = map[string]interface{}{"schedule": svc.Schedule, "jobTemplate": map[string]interface{}{"spec": spec}}
			delete(spec["jobTemplate"].(map[string]interface{})["spec"].(map[string]interface{}), "replicas")
		case manifest.WorkloadDaemon:
			kind = "DaemonSet"
			delete(spec, "replicas")
		}
		res := map[string]interface{}{
			"apiVersion": apiVer, "kind": kind,
			"metadata": map[string]interface{}{"name": svc.Name, "namespace": ns, "labels": labels},
			"spec": spec,
		}
		d, _ := yaml.Marshal(res)
		docs = append(docs, string(d))

		if len(svc.Ports) > 0 {
			var ports []interface{}
			for _, p := range svc.Ports {
				ports = append(ports, map[string]interface{}{"port": p.Expose, "targetPort": p.Expose, "protocol": "TCP"})
			}
			svcRes, _ := yaml.Marshal(map[string]interface{}{
				"apiVersion": "v1", "kind": "Service",
				"metadata": map[string]interface{}{"name": svc.Name, "namespace": ns},
				"spec": map[string]interface{}{"selector": labels, "ports": ports},
			})
			docs = append(docs, string(svcRes))
		}
	}
	return []byte("# Generated by StratonMesh\n---\n" + strings.Join(docs, "\n---\n")), nil
}

func buildContainer(svc manifest.Service) map[string]interface{} {
	c := map[string]interface{}{"name": svc.Name, "image": svc.Image}
	var ports []interface{}
	for _, p := range svc.Ports { ports = append(ports, map[string]interface{}{"containerPort": p.Expose}) }
	if len(ports) > 0 { c["ports"] = ports }
	var env []interface{}
	for k, v := range svc.Env {
		env = append(env, map[string]interface{}{"name": k, "value": v})
	}
	if len(env) > 0 { c["env"] = env }
	if svc.Resources.CPU != "" || svc.Resources.Memory != "" {
		r := map[string]string{}
		if svc.Resources.CPU != "" { r["cpu"] = svc.Resources.CPU }
		if svc.Resources.Memory != "" { r["memory"] = svc.Resources.Memory }
		c["resources"] = map[string]interface{}{"requests": r, "limits": r}
	}
	if svc.HealthCheck.Liveness != nil && svc.HealthCheck.Liveness.HTTP != "" {
		port := 80; if len(svc.Ports) > 0 { port = svc.Ports[0].Expose }
		c["livenessProbe"] = map[string]interface{}{"httpGet": map[string]interface{}{"path": svc.HealthCheck.Liveness.HTTP, "port": port}}
	}
	if svc.Command != "" { c["command"] = strings.Fields(svc.Command) }
	return c
}

func (a *Adapter) Apply(ctx context.Context, stack *manifest.Stack) error {
	data, err := a.Generate(ctx, stack)
	if err != nil { return err }
	a.logger.Infow("kubernetes manifests generated", "stack", stack.Name, "bytes", len(data))
	// TODO: client-go server-side apply
	return nil
}
func (a *Adapter) Status(ctx context.Context, id string) (*orchestrator.AdapterStatus, error) { return &orchestrator.AdapterStatus{}, nil }
func (a *Adapter) Destroy(ctx context.Context, id string) error { return nil }
func (a *Adapter) Diff(ctx context.Context, d, act *manifest.Stack) (*orchestrator.DiffResult, error) { return &orchestrator.DiffResult{}, nil }
func (a *Adapter) Rollback(ctx context.Context, id, v string) error { return nil }
