package terraform

import (
	"context"
	"fmt"
	"io"
	"strings"

	"github.com/selvamani/stratonmesh/pkg/manifest"
	"github.com/selvamani/stratonmesh/pkg/orchestrator"
	"go.uber.org/zap"
)

type Adapter struct {
	logger   *zap.SugaredLogger
	provider string // aws, gcp, azure
}

var _ orchestrator.PlatformAdapter = (*Adapter)(nil)

func New(logger *zap.SugaredLogger, provider string) *Adapter {
	if provider == "" { provider = "aws" }
	return &Adapter{logger: logger, provider: provider}
}

func (a *Adapter) Name() string { return "terraform" }

func (a *Adapter) Generate(ctx context.Context, stack *manifest.Stack) ([]byte, error) {
	var hcl strings.Builder
	hcl.WriteString(fmt.Sprintf("# Generated by StratonMesh: %s v%s\n", stack.Name, stack.Version))
	hcl.WriteString(fmt.Sprintf("# Provider: %s\n\n", a.provider))

	switch a.provider {
	case "aws":
		a.generateAWS(&hcl, stack)
	case "gcp":
		a.generateGCP(&hcl, stack)
	default:
		a.generateAWS(&hcl, stack)
	}
	return []byte(hcl.String()), nil
}

func (a *Adapter) generateAWS(hcl *strings.Builder, stack *manifest.Stack) {
	hcl.WriteString("provider \"aws\" {\n  region = var.region\n}\n\n")
	hcl.WriteString(fmt.Sprintf("variable \"region\" {\n  default = \"us-east-1\"\n}\n\n"))

	for _, svc := range stack.Services {
		if !svc.IsEnabled() { continue }
		switch svc.InferType() {
		case manifest.WorkloadStateful:
			if strings.Contains(svc.Image, "postgres") || strings.Contains(svc.Image, "mysql") || strings.Contains(svc.Image, "mariadb") {
				hcl.WriteString(fmt.Sprintf("resource \"aws_rds_instance\" \"%s\" {\n", svc.Name))
				engine := "postgres"
				if strings.Contains(svc.Image, "mysql") || strings.Contains(svc.Image, "mariadb") { engine = "mysql" }
				hcl.WriteString(fmt.Sprintf("  engine         = \"%s\"\n", engine))
				hcl.WriteString(fmt.Sprintf("  instance_class = \"db.t3.medium\"\n"))
				hcl.WriteString(fmt.Sprintf("  allocated_storage = 50\n"))
				hcl.WriteString(fmt.Sprintf("  tags = { stratonmesh_stack = \"%s\" }\n", stack.Name))
				hcl.WriteString("}\n\n")
			} else {
				a.generateECSService(hcl, svc, stack)
			}
		case manifest.WorkloadBatch:
			hcl.WriteString(fmt.Sprintf("resource \"aws_batch_job_definition\" \"%s\" {\n", svc.Name))
			hcl.WriteString(fmt.Sprintf("  name = \"%s\"\n  type = \"container\"\n", svc.Name))
			hcl.WriteString(fmt.Sprintf("  container_properties = jsonencode({\n    image = \"%s\"\n    vcpus = 2\n    memory = 4096\n  })\n", svc.Image))
			hcl.WriteString("}\n\n")
		default:
			a.generateECSService(hcl, svc, stack)
		}
	}
}

func (a *Adapter) generateECSService(hcl *strings.Builder, svc manifest.Service, stack *manifest.Stack) {
	hcl.WriteString(fmt.Sprintf("resource \"aws_ecs_service\" \"%s\" {\n", svc.Name))
	hcl.WriteString(fmt.Sprintf("  name            = \"%s\"\n", svc.Name))
	hcl.WriteString(fmt.Sprintf("  cluster         = var.ecs_cluster_arn\n"))
	hcl.WriteString(fmt.Sprintf("  desired_count   = %d\n", svc.DefaultReplicas()))
	hcl.WriteString(fmt.Sprintf("  launch_type     = \"FARGATE\"\n"))
	hcl.WriteString(fmt.Sprintf("  tags = { stratonmesh_stack = \"%s\" }\n", stack.Name))
	hcl.WriteString("}\n\n")
}

func (a *Adapter) generateGCP(hcl *strings.Builder, stack *manifest.Stack) {
	hcl.WriteString("provider \"google\" {\n  project = var.project_id\n  region  = var.region\n}\n\n")
	for _, svc := range stack.Services {
		if !svc.IsEnabled() { continue }
		hcl.WriteString(fmt.Sprintf("resource \"google_cloud_run_service\" \"%s\" {\n", svc.Name))
		hcl.WriteString(fmt.Sprintf("  name     = \"%s\"\n  location = var.region\n", svc.Name))
		hcl.WriteString(fmt.Sprintf("  template {\n    spec {\n      containers {\n        image = \"%s\"\n      }\n    }\n  }\n", svc.Image))
		hcl.WriteString("}\n\n")
	}
}

func (a *Adapter) Apply(ctx context.Context, stack *manifest.Stack) error {
	data, _ := a.Generate(ctx, stack)
	a.logger.Infow("terraform HCL generated", "stack", stack.Name, "bytes", len(data))
	// TODO: terraform init + plan + apply
	return nil
}
func (a *Adapter) Status(ctx context.Context, id string) (*orchestrator.AdapterStatus, error) { return &orchestrator.AdapterStatus{}, nil }
func (a *Adapter) Stop(ctx context.Context, id string) error    { return nil }
func (a *Adapter) Start(ctx context.Context, id string) error   { return nil }
func (a *Adapter) Restart(ctx context.Context, id string) error { return nil }
func (a *Adapter) Down(ctx context.Context, id string) error    { return nil }
func (a *Adapter) Destroy(ctx context.Context, id string) error { return nil }
func (a *Adapter) Diff(ctx context.Context, d, act *manifest.Stack) (*orchestrator.DiffResult, error) { return &orchestrator.DiffResult{}, nil }
func (a *Adapter) Rollback(ctx context.Context, id, v string) error { return nil }
func (a *Adapter) Inspect(ctx context.Context, stackID, service string) (*orchestrator.ServiceDetail, error) {
	return &orchestrator.ServiceDetail{Name: service, Platform: "terraform"}, nil
}
func (a *Adapter) Logs(ctx context.Context, stackID, service string, tail int) (string, error) {
	return "# terraform: remote execution — logs not available locally", nil
}
func (a *Adapter) LogStream(_ context.Context, _, _ string) (io.ReadCloser, error) {
	return io.NopCloser(strings.NewReader("# terraform: remote execution — logs not available locally\n")), nil
}
