package pulumi

import (
	"context"
	"fmt"
	"strings"

	"github.com/stratonmesh/stratonmesh/pkg/manifest"
	"github.com/stratonmesh/stratonmesh/pkg/orchestrator"
	"go.uber.org/zap"
)

// Adapter implements PlatformAdapter for Pulumi.
type Adapter struct {
	logger *zap.SugaredLogger
}

var _ orchestrator.PlatformAdapter = (*Adapter)(nil)

func New(logger *zap.SugaredLogger) *Adapter { return &Adapter{logger: logger} }
func (a *Adapter) Name() string              { return "pulumi" }

func (a *Adapter) Generate(ctx context.Context, stack *manifest.Stack) ([]byte, error) {
	var ts strings.Builder
	ts.WriteString(fmt.Sprintf("// Generated by StratonMesh: %s v%s\n", stack.Name, stack.Version))
	ts.WriteString("import * as aws from \"@pulumi/aws\";\nimport * as pulumi from \"@pulumi/pulumi\";\n\n")
	for _, svc := range stack.Services {
		if !svc.IsEnabled() {
			continue
		}
		if svc.InferType() == manifest.WorkloadStateful && strings.Contains(svc.Image, "postgres") {
			ts.WriteString(fmt.Sprintf("const %s = new aws.rds.Instance(\"%s\", {\n", svc.Name, svc.Name))
			ts.WriteString("  engine: \"postgres\", engineVersion: \"16\", instanceClass: \"db.t3.medium\",\n")
			ts.WriteString(fmt.Sprintf("  allocatedStorage: 50, tags: { stratonmesh_stack: \"%s\" },\n});\n\n", stack.Name))
		} else {
			ts.WriteString(fmt.Sprintf("const %s = new aws.ecs.Service(\"%s\", {\n", svc.Name, svc.Name))
			ts.WriteString(fmt.Sprintf("  desiredCount: %d, launchType: \"FARGATE\",\n});\n\n", svc.DefaultReplicas()))
		}
		ts.WriteString(fmt.Sprintf("export const %sId = %s.id;\n", svc.Name, svc.Name))
	}
	return []byte(ts.String()), nil
}

func (a *Adapter) Apply(ctx context.Context, stack *manifest.Stack) error {
	data, err := a.Generate(ctx, stack)
	if err != nil {
		return err
	}
	a.logger.Infow("pulumi program generated", "stack", stack.Name, "bytes", len(data))
	return nil
}

func (a *Adapter) Status(ctx context.Context, id string) (*orchestrator.AdapterStatus, error) {
	return &orchestrator.AdapterStatus{}, nil
}
func (a *Adapter) Destroy(ctx context.Context, id string) error { return nil }
func (a *Adapter) Diff(ctx context.Context, d, act *manifest.Stack) (*orchestrator.DiffResult, error) {
	return &orchestrator.DiffResult{}, nil
}
func (a *Adapter) Rollback(ctx context.Context, id, v string) error { return nil }
